/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useGLTF, 

 } from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-kaykit-2/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
<group rotation={[Math.PI / 2, 0, 0,]} >
<mesh geometry={nodes.Cylinder017.geometry} material={materials['GreenDark.003']} />
<mesh geometry={nodes.Cylinder017_1.geometry} material={materials['BrownDark.035']} />
</group>

    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/tree-kaykit-2/model.gltf')